#!/usr/bin/env bash
# protobuild.sh - Lightweight modular build system
# version: 2.0.0-proto
# Lean version of build.sh with core functionality only

set -euo pipefail

# Colors
readonly green=$'\033[32m'; readonly blue=$'\033[34m'; readonly yellow=$'\033[33m'
readonly red=$'\033[31m'; readonly x=$'\033[38;5;244m'

# Core configuration
declare -A config=(
    ["PROJECT_NAME"]="fx-buildsh"
    ["PROJECT_VERSION"]="2.0.0-proto"
    ["OUTPUT_FILE"]="build-result.sh"
    ["PARTS_DIR"]="parts"
    ["BUILD_MAP"]="parts/build.map"
)

# Load config from build.conf if it exists
load_config() {
    [[ -f "build.conf" ]] || return 0
    while IFS='=' read -r key value; do
        [[ -n "$key" && ! "$key" =~ ^[[:space:]]*# ]] && {
            # Remove quotes from value if present
            value=$(echo "$value" | sed 's/^"\(.*\)"$/\1/')
            config["$key"]="$value"
        }
    done < <(grep -v '^\s*#\|^\s*$' build.conf)
}

# Compact logo using toilet future font
show_logo() {
    if command -v toilet >/dev/null 2>&1; then
        printf "%s" "$blue"
        toilet -f future "${config[PROJECT_NAME]}"
        printf "%s" "$x"
    else
        printf "%s%s%s v%s\n" "$blue" "${config[PROJECT_NAME]}" "$x" "${config[PROJECT_VERSION]}"
    fi
}

# Error handling
die() { printf "%sError:%s %s\n" "$red" "$x" "$*" >&2; exit 1; }
warn() { printf "%sWarning:%s %s\n" "$yellow" "$x" "$*" >&2; }
info() { printf "%sInfo:%s %s\n" "$blue" "$x" "$*"; }

# Validate syntax of shell file
validate_shell() {
    local file="$1"
    bash -n "$file" 2>/dev/null || die "Syntax error in $file"
}

# Get module list from build map
get_modules() {
    local map_file="${config[BUILD_MAP]}"
    [[ -f "$map_file" ]] || die "Build map not found: $map_file"
    
    while IFS=':' read -r pos file; do
        [[ "$pos" =~ ^[[:space:]]*[0-9]+[[:space:]]*$ ]] || continue
        file=$(echo "$file" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        [[ -n "$file" && -f "${config[PARTS_DIR]}/$file" ]] && echo "$file"
    done < "$map_file"
}

# Build main function
do_build() {
    local output="${config[OUTPUT_FILE]}"
    local parts_dir="${config[PARTS_DIR]}"
    
    [[ -d "$parts_dir" ]] || die "Parts directory not found: $parts_dir"
    
    # Create output with header
    {
        echo "#!/usr/bin/env bash"
        echo "# Generated by ${config[PROJECT_NAME]} v${config[PROJECT_VERSION]}"
        echo "# $(date)"
        echo
    } > "$output"
    
    # Process modules
    local count=0
    while read -r module; do
        local module_path="$parts_dir/$module"
        validate_shell "$module_path"
        
        echo "# === $module ===" >> "$output"
        cat "$module_path" >> "$output"
        echo >> "$output"
        ((count++))
    done < <(get_modules)
    
    chmod +x "$output"
    printf "%s✓ Built %s with %d modules%s\n" "$green" "$output" "$count" "$x"
}

# List modules
do_list() {
    printf "%sModules in build order:%s\n" "$green" "$x"
    local pos=1
    while read -r module; do
        printf "  %02d: %s\n" "$pos" "$module"
        ((pos++))
    done < <(get_modules)
}

# Insert module at position
do_insert() {
    local file="$1" pos="${2:-99}"
    [[ -n "$file" ]] || die "Usage: insert <filename> [position]"
    [[ -f "${config[PARTS_DIR]}/$file" ]] || die "Module not found: $file"
    
    local map_file="${config[BUILD_MAP]}"
    local temp_map=$(mktemp)
    
    # Insert at position
    {
        awk -v pos="$pos" -v file="$file" -F: '
        BEGIN { inserted = 0 }
        {
            curr_pos = int($1)
            if (!inserted && curr_pos >= pos) {
                printf "%02d : %s\n", pos, file
                inserted = 1
            }
            if (curr_pos != pos) print
        }
        END { if (!inserted) printf "%02d : %s\n", pos, file }
        ' "$map_file"
    } > "$temp_map"
    
    mv "$temp_map" "$map_file"
    info "Inserted $file at position $pos"
}

# Swap module positions
do_swap() {
    local pos1="$1" pos2="$2"
    [[ -n "$pos1" && -n "$pos2" ]] || die "Usage: swap <pos1> <pos2>"
    
    local map_file="${config[BUILD_MAP]}"
    local temp_map=$(mktemp)
    
    awk -v p1="$pos1" -v p2="$pos2" -F: '
    { pos[int($1)] = $2 }
    END {
        temp = pos[p1]; pos[p1] = pos[p2]; pos[p2] = temp
        for (p in pos) printf "%02d : %s\n", p, pos[p]
    }
    ' "$map_file" | sort -n > "$temp_map"
    
    mv "$temp_map" "$map_file"
    info "Swapped positions $pos1 and $pos2"
}

# Update build map from filesystem
do_remap() {
    local parts_dir="${config[PARTS_DIR]}"
    local map_file="${config[BUILD_MAP]}"
    
    [[ -d "$parts_dir" ]] || die "Parts directory not found: $parts_dir"
    
    # Generate new map
    find "$parts_dir" -name "*.sh" -type f | sort | {
        pos=1
        while read -r file; do
            basename_file=$(basename "$file")
            printf "%02d : %s\n" "$pos" "$basename_file"
            ((pos++))
        done
    } > "$map_file"
    
    info "Regenerated build map with $(wc -l < "$map_file") modules"
}

# Show status
do_status() {
    show_logo
    printf "\n%sProject:%s %s v%s\n" "$blue" "$x" "${config[PROJECT_NAME]}" "${config[PROJECT_VERSION]}"
    printf "%sParts:%s %s\n" "$blue" "$x" "${config[PARTS_DIR]}"
    printf "%sOutput:%s %s\n" "$blue" "$x" "${config[OUTPUT_FILE]}"
    
    if [[ -f "${config[BUILD_MAP]}" ]]; then
        local count=$(get_modules | wc -l)
        printf "%sModules:%s %d ready\n" "$blue" "$x" "$count"
    else
        printf "%sModules:%s No build map found\n" "$red" "$x"
    fi
}

# XDG+ Installation System - Lightweight Version

# Get XDG directories for installation
get_install_dirs() {
    local scope="${1:-user}"
    
    case "$scope" in
        (user)
            echo "lib_dir=${XDG_DATA_HOME:-$HOME/.local/share}/fx/buildsh"
            echo "bin_dir=${XDG_BIN_HOME:-$HOME/.local/bin}/fx"
            echo "registry=${XDG_DATA_HOME:-$HOME/.local/share}/fx/install.registry"
            ;;
        (system)
            echo "lib_dir=/usr/local/lib/fx/buildsh"  
            echo "bin_dir=/usr/local/bin/fx"
            echo "registry=/usr/local/share/fx/install.registry"
            ;;
    esac
}

# Create installation record
create_install_record() {
    local registry="$1" install_id="$2" install_path="$3" version="$4"
    
    mkdir -p "$(dirname "$registry")"
    
    # Remove existing entry, add new one
    if [[ -f "$registry" ]]; then
        grep -v "^$install_id:" "$registry" > "${registry}.tmp" 2>/dev/null || true
        mv "${registry}.tmp" "$registry"
    fi
    
    printf "%s:%s:%s:%s:%s:%s\n" "$install_id" "$install_path" "$install_path" "$version" "$(date +%s)" "${config[PROJECT_NAME]}" >> "$registry"
}

# Remove installation record
remove_install_record() {
    local registry="$1" install_id="$2"
    
    if [[ -f "$registry" ]]; then
        grep -v "^$install_id:" "$registry" > "${registry}.tmp" 2>/dev/null || true
        mv "${registry}.tmp" "$registry"
    fi
}

# Check if installation exists
install_exists() {
    local registry="$1" install_id="$2"
    [[ -f "$registry" ]] && grep -q "^$install_id:" "$registry"
}

# Install function
do_install() {
    local scope="user" force=false org="fx" namespace="protobuild"
    
    # Parse options
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --system|--global) scope="system"; shift ;;
            --user) scope="user"; shift ;;
            --force|-f) force=true; shift ;;
            --org) org="$2"; shift 2 ;;
            --namespace) namespace="$2"; shift 2 ;;
            *) die "Unknown install option: $1" ;;
        esac
    done
    
    # System install requires root
    if [[ "$scope" == "system" && $EUID -ne 0 ]]; then
        die "System installation requires root privileges. Try: sudo $0 install --system"
    fi
    
    # Get directories
    local dirs
    dirs=$(get_install_dirs "$scope")
    local lib_dir=$(echo "$dirs" | grep "^lib_dir=" | cut -d= -f2-)
    local bin_dir=$(echo "$dirs" | grep "^bin_dir=" | cut -d= -f2-)
    local registry=$(echo "$dirs" | grep "^registry=" | cut -d= -f2-)
    
    local install_id="${org}-${namespace}"
    
    printf "%sInstalling %s %s (%s)%s\n" "$blue" "${config[PROJECT_NAME]}" "${config[PROJECT_VERSION]}" "$scope" "$x"
    printf "Target: %s\n" "$lib_dir"
    printf "Command: %s\n" "$install_id"
    
    # Check for existing installation
    if install_exists "$registry" "$install_id" && [[ "$force" != "true" ]]; then
        die "Installation '$install_id' already exists. Use --force to overwrite."
    fi
    
    # Build if needed
    local output="${config[OUTPUT_FILE]}"
    if [[ ! -f "$output" ]]; then
        info "Building first..."
        do_build
    fi
    
    # Create directories
    mkdir -p "$lib_dir" "$bin_dir"
    
    # Install script
    local script_path="$lib_dir/$(basename "$output")"
    cp "$output" "$script_path"
    chmod 755 "$script_path"
    info "Installed: $script_path"
    
    # Install config if exists
    if [[ -f "build.conf" ]]; then
        cp "build.conf" "$lib_dir/"
        info "Installed: $lib_dir/build.conf"
    fi
    
    # Create symlink
    local bin_path="$bin_dir/$install_id"
    ln -sf "$script_path" "$bin_path"
    info "Created command: $install_id"
    
    # Record installation
    create_install_record "$registry" "$install_id" "$script_path" "${config[PROJECT_VERSION]}"
    
    printf "\n%s✓ Installation complete!%s\n" "$green" "$x"
    if [[ "$scope" == "user" ]]; then
        printf "Add to PATH: export PATH=\"$bin_dir:\$PATH\"\n"
    fi
}

# Uninstall function
do_uninstall() {
    local scope="user" force=false org="fx" namespace="protobuild"
    
    # Parse options
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --system|--global) scope="system"; shift ;;
            --user) scope="user"; shift ;;
            --force|-f) force=true; shift ;;
            --org) org="$2"; shift 2 ;;
            --namespace) namespace="$2"; shift 2 ;;
            *) die "Unknown uninstall option: $1" ;;
        esac
    done
    
    # Get directories
    local dirs
    dirs=$(get_install_dirs "$scope")
    local lib_dir=$(echo "$dirs" | grep "^lib_dir=" | cut -d= -f2-)
    local bin_dir=$(echo "$dirs" | grep "^bin_dir=" | cut -d= -f2-)
    local registry=$(echo "$dirs" | grep "^registry=" | cut -d= -f2-)
    
    local install_id="${org}-${namespace}"
    
    printf "%sUninstalling %s (%s)%s\n" "$blue" "$install_id" "$scope" "$x"
    
    # Check if installation exists
    if ! install_exists "$registry" "$install_id"; then
        die "Installation '$install_id' not found"
    fi
    
    # Confirm unless forced
    if [[ "$force" != "true" ]]; then
        printf "Remove installation? (y/N): "
        read -r confirm
        if [[ "$confirm" != [yY] ]]; then
            info "Uninstall cancelled"
            return 0
        fi
    fi
    
    # Remove files
    local bin_path="$bin_dir/$install_id"
    [[ -L "$bin_path" ]] && { rm -f "$bin_path"; info "Removed: $bin_path"; }
    
    # Find and remove installed files
    if [[ -f "$registry" ]]; then
        local install_info
        install_info=$(grep "^$install_id:" "$registry" | head -n1)
        if [[ -n "$install_info" ]]; then
            local script_path=$(echo "$install_info" | cut -d: -f2)
            [[ -f "$script_path" ]] && { rm -f "$script_path"; info "Removed: $script_path"; }
            
            local config_path="$(dirname "$script_path")/build.conf"
            [[ -f "$config_path" ]] && { rm -f "$config_path"; info "Removed: $config_path"; }
            
            # Clean up empty directories
            local install_dir="$(dirname "$script_path")"
            [[ -d "$install_dir" && -z "$(ls -A "$install_dir" 2>/dev/null)" ]] && rmdir "$install_dir" 2>/dev/null
        fi
    fi
    
    # Remove registry record
    remove_install_record "$registry" "$install_id"
    
    printf "\n%s✓ Uninstall complete!%s\n" "$green" "$x"
}

# Help
show_help() {
    cat << EOF
${blue}protobuild.sh${x} - Lightweight modular build system

${green}USAGE:${x}
  ./protobuild.sh <command> [options]

${green}COMMANDS:${x}
  build      Build output file from modules
  list       Show modules in build order
  insert     Insert module at position
  swap       Swap two module positions
  remap      Regenerate build map from filesystem
  install    Install to XDG-compliant directories
  uninstall  Remove installation
  status     Show project status
  logo       Show project logo
  help       Show this help

${green}EXAMPLES:${x}
  ./protobuild.sh build                    # Build project
  ./protobuild.sh list                     # List modules
  ./protobuild.sh insert new_module.sh 5   # Insert at position 5
  ./protobuild.sh swap 3 7                 # Swap positions 3 and 7
  ./protobuild.sh remap                    # Regenerate build map
  ./protobuild.sh install                  # Install as fx-protobuild
  ./protobuild.sh uninstall --force        # Force uninstall

${green}FILES:${x}
  build.conf         Configuration file
  parts/build.map    Module build order
  parts/             Module directory
  build-result.sh    Generated output

Lightweight version focused on core functionality.
For advanced features, use the full build.sh script.
EOF
}

# Main command dispatch
main() {
    load_config
    
    case "${1:-help}" in
        build) do_build ;;
        list) do_list ;;
        insert) shift; do_insert "$@" ;;
        swap) shift; do_swap "$@" ;;
        remap) do_remap ;;
        install) shift; do_install "$@" ;;
        uninstall) shift; do_uninstall "$@" ;;
        status) do_status ;;
        logo) show_logo ;;
        help|--help|-h|"") show_help ;;
        *) die "Unknown command: $1. Use 'help' for usage." ;;
    esac
}

# Run if executed directly
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"